name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/laravel_docker

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверяем код
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Логин в GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Шаг 3: Сборка Docker образа
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:latest .

      # Шаг 4: Пуш Docker образа
      - name: Push Docker image
        run: docker push $IMAGE_NAME:latest

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/laravel_docker:latest

            # Удаляем все контейнеры на порту 8000
            PORT_CONFLICT=$(docker ps -q --filter "publish=8000")
            if [ -n "$PORT_CONFLICT" ]; then
              docker stop $PORT_CONFLICT
              docker rm $PORT_CONFLICT
            fi

            # Удаляем контейнер с именем laravel-app, если он остался
            docker stop go-app || true
            docker rm go-app || true

            # Пуллим новый образ
            docker pull $IMAGE_NAME

            # Запускаем контейнер
            docker run -d --name laravel-app -p 8000:80 $IMAGE_NAME
